import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-slate-900 text-slate-300">
        <header
          className="flex flex-row items-center justify-between bg-slate-900 sticky top-0 p-4 mb-6 shadow-lg"
          style={{ zIndex: "1" }}
        >
          <ul className="flex flex-row gap-16 items-center justify-end font-semibold">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/products">Products</Link>
            </li>
            <li>
              <Link href="/document">Document</Link>
            </li>
          </ul>
          <Link
            href="/products"
            className="bg-slate-700 rounded p-2 w-32 text-blue-200 text-center font-bold hover:bg-blue-700 hover:text-white"
          >
            Get Started
          </Link>
        </header>
        {children}
        <footer className="shadow-lg">
          <div className="flex flex-row items-start justify-center gap-32 p-4 mt-8">
            <div className="flex flex-col text-left justify-start p-4">
              <h3 className="font-semibold">Products</h3>
              <ul>
                <li>
                  <Link href="/products/summarize-text">Summarize Text</Link>
                </li>
                <li>
                  <Link href="/products/analyze-sentiment">
                    Analyze Sentiment
                  </Link>
                </li>
                <li>
                  <Link href="/products/extract-keywords">
                    Extract Keywords
                  </Link>
                </li>
              </ul>
            </div>
            <div className="flex flex-col text-left justify-start p-4">
              <h3 className="font-semibold">APIs</h3>
              <ul>
                <li>
                  <Link href="/document">Documents</Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="mt-2 p-4 text-center font-medium">
            &copy;copyright reserved by KAI
          </div>
        </footer>
      </body>
    </html>
  );
}
